### ISSUE TITLE
m4a to wav converter problem. 

### ISSUE THREAD

**Issue by GamebP** [jschuhmann47/youtubeToWav#1] opened 2023-01-09 14:14 UTC
Error when downloaded and it wont transfer ot tp wav.
Don't ask me to reinstall the packages again. i already have them.

WARNING: ehbmC1irQuY: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
Traceback (most recent call last):
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
                            ^^^^^^^^^^^^
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 275, in run
    filecodec = self.get_audio_codec(path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 166, in get_audio_codec
    raise PostProcessingError('ffprobe/avprobe and ffmpeg/avconv not found. Please install one.')
youtube_dl.utils.PostProcessingError: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kalvis\Desktop\python\wav.py", line 16, in <module>
    ydl.download([url])
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2050, in process_info
    self.post_process(filename, info_dict)
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2117, in post_process
    self.report_error(e.msg)
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Kalvis\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

**Comment by jschuhmann47** [comment] 2023-01-13 23:52
I have checked your error, it seems that `ffmpeg` needs to be installed on the device that you are using. The `ffmpeg-python` library does not include it. I had it previously installed so I haven't noticed. I'll add it to the Readme.

If you are on Windows you can install it from the official website and then add it to PATH.
You can install it from [here](https://ffmpeg.org/), and [here](https://github.com/ytdl-org/youtube-dl#on-windows-how-should-i-set-up-ffmpeg-and-youtube-dl-where-should-i-put-the-exe-files) are instructions for adding it to the PATH. 

You can alternatively put the `ffmpeg.exe` and `ffprobe.exe` in the script repository, it should work but it's more messy since it'll only work with this script and it won't with other programs that you might download in the future.

Also I have recently updated the script and now it uses `yt-dlp` instead of `youtube-dl` (I put that on the Readme), but it shouldn't be the problem.

Please let me know if the problem is solved.

**Comment by jschuhmann47** [comment] 2023-01-20 17:22
Closing for now, feel free to ask if needed

**Closed as completed by jschuhmann47** 2023-01-20 17:22 UTC
